"use client";

import { FormEvent, useState } from "react";

type Summary = { profileRef: string; demoIdentifier: string; maskedDisplayName: string; active: boolean; creditorCount: number; debtCount: number; offerCount: number };
type Offer = { offerRef: string; kind: "CASH" | "INSTALLMENT"; totalAmountInCents: number; downPaymentAmountInCents: number; installmentCount: number; installmentAmountInCents: number; firstDueDate: string; expiresAt: string; status: "AVAILABLE" | "EXPIRED" | "DISABLED" };
type Scenario = { demoConfirmation: true; profile: { profileRef: string; demoIdentifier: string; maskedDisplayName: string }; challenge: { challengeRef: string; prompt: string; correctOptionRef: string; options: { optionRef: string; label: string }[] }; creditor: { creditorRef: string; displayName: string }; debtor: { debtorRef: string }; debt: { debtRef: string; description: string; amountInCents: number; dueDate: string; status: "OPEN" | "DISPUTED" | "PAID" }; offers: Offer[] };
const empty = (): Scenario => ({ demoConfirmation: true, profile: { profileRef: "", demoIdentifier: "DEMO-", maskedDisplayName: "Pessoa Demonstração " }, challenge: { challengeRef: "", prompt: "", correctOptionRef: "", options: [{ optionRef: "option-a", label: "Opção A demo" }, { optionRef: "option-b", label: "Opção B demo" }] }, creditor: { creditorRef: "", displayName: "Credor Demonstrativo " }, debtor: { debtorRef: "" }, debt: { debtRef: "", description: "Contrato fictício ", amountInCents: 10000, dueDate: "2099-01-01", status: "OPEN" }, offers: [{ offerRef: "", kind: "CASH", totalAmountInCents: 10000, downPaymentAmountInCents: 10000, installmentCount: 1, installmentAmountInCents: 10000, firstDueDate: "2099-01-10", expiresAt: "2099-01-10T23:59:59.000Z", status: "AVAILABLE" }] });

export function ScenarioManager({ initial }: { initial: Summary[] }) {
  const [items, setItems] = useState(initial); const [form, setForm] = useState<Scenario>(empty()); const [editing, setEditing] = useState<string>(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const setSection = <K extends keyof Scenario>(section: K, value: Scenario[K]) => setForm((current) => ({ ...current, [section]: value }));
  async function refresh() { const response = await fetch("/api/v1/internal/scenarios", { cache: "no-store" }); if (response.ok) setItems(await response.json()); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const url = editing ? `/api/v1/internal/scenarios/${encodeURIComponent(editing)}` : "/api/v1/internal/scenarios"; try { const response = await fetch(url, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Não foi possível salvar."); setMessage(editing ? "Cenário versionado e atualizado." : "Cenário fictício criado."); setEditing(undefined); setForm(empty()); await refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Não foi possível salvar."); } finally { setBusy(false); } }
  async function edit(profileRef: string) { const response = await fetch(`/api/v1/internal/scenarios/${encodeURIComponent(profileRef)}`, { cache: "no-store" }); const value = await response.json(); if (!response.ok) { setMessage(value.error?.message ?? "Falha ao carregar."); return; } setEditing(profileRef); setForm({ demoConfirmation: true, profile: { profileRef: value.profileRef, demoIdentifier: value.demoIdentifier, maskedDisplayName: value.maskedDisplayName }, challenge: { challengeRef: value.challenge.challengeRef, prompt: value.challenge.prompt, correctOptionRef: value.challenge.correctOptionRef, options: value.challenge.options }, creditor: value.creditor, debtor: value.debtor, debt: { debtRef: value.debt.debtRef, description: value.debt.description, amountInCents: value.debt.amountInCents, dueDate: value.debt.dueDate, status: value.debt.status }, offers: value.offers.map((item: Offer & { active: boolean; providerVersion: string }) => ({ offerRef: item.offerRef, kind: item.kind, totalAmountInCents: item.totalAmountInCents, downPaymentAmountInCents: item.downPaymentAmountInCents, installmentCount: item.installmentCount, installmentAmountInCents: item.installmentAmountInCents, firstDueDate: item.firstDueDate, expiresAt: item.expiresAt, status: item.status })) }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function toggle(item: Summary) { const response = await fetch(`/api/v1/internal/scenarios/${encodeURIComponent(item.profileRef)}/status`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !item.active, demoConfirmation: true }) }); if (!response.ok) setMessage("Não foi possível alterar o status."); await refresh(); }
  const updateOffer = (index: number, patch: Partial<Offer>) => setForm((current) => ({ ...current, offers: current.offers.map((offer, position) => position === index ? { ...offer, ...patch } : offer) }));
  return <main className="internal-page"><div className="demo-ribbon">SANDBOX INTERNO — SOMENTE DADOS FICTÍCIOS — SEM VALOR FINANCEIRO</div><header className="internal-header"><div><p className="eyebrow">JF Demo</p><h1>Construtor de cenários</h1></div><a className="button secondary" href="/demo/jf-demo" target="_blank" rel="noreferrer">Testar demonstração</a></header><section className="internal-layout"><form className="panel internal-form" onSubmit={submit}><h2>{editing ? "Editar cenário" : "Novo cenário completo"}</h2><p>Referências são opacas. Alterações de desafio, dívida e propostas criam novas versões e não alteram aceites anteriores.</p>
    <fieldset><legend>1. Perfil fictício</legend><label>Referência<input value={form.profile.profileRef} disabled={!!editing} onChange={(e) => setSection("profile", { ...form.profile, profileRef: e.target.value })}/></label><label>Identificador DEMO-<input value={form.profile.demoIdentifier} onChange={(e) => setSection("profile", { ...form.profile, demoIdentifier: e.target.value.toUpperCase() })}/></label><label>Nome mascarado<input value={form.profile.maskedDisplayName} onChange={(e) => setSection("profile", { ...form.profile, maskedDisplayName: e.target.value })}/></label></fieldset>
    <fieldset><legend>2. Desafio</legend><label>Referência<input value={form.challenge.challengeRef} onChange={(e) => setSection("challenge", { ...form.challenge, challengeRef: e.target.value })}/></label><label>Pergunta<input value={form.challenge.prompt} onChange={(e) => setSection("challenge", { ...form.challenge, prompt: e.target.value })}/></label>{form.challenge.options.map((option, index) => <div className="inline-fields" key={index}><label>Option ref<input value={option.optionRef} onChange={(e) => setSection("challenge", { ...form.challenge, options: form.challenge.options.map((item, position) => position === index ? { ...item, optionRef: e.target.value } : item) })}/></label><label>Rótulo<input value={option.label} onChange={(e) => setSection("challenge", { ...form.challenge, options: form.challenge.options.map((item, position) => position === index ? { ...item, label: e.target.value } : item) })}/></label></div>)}<label>Resposta correta<select value={form.challenge.correctOptionRef} onChange={(e) => setSection("challenge", { ...form.challenge, correctOptionRef: e.target.value })}><option value="">Selecione</option>{form.challenge.options.map((option) => <option key={option.optionRef} value={option.optionRef}>{option.label}</option>)}</select></label></fieldset>
    <fieldset><legend>3. Credor e conta</legend><div className="inline-fields"><label>Creditor ref<input value={form.creditor.creditorRef} onChange={(e) => setSection("creditor", { ...form.creditor, creditorRef: e.target.value })}/></label><label>Nome demonstrativo<input value={form.creditor.displayName} onChange={(e) => setSection("creditor", { ...form.creditor, displayName: e.target.value })}/></label></div><label>Debtor ref<input value={form.debtor.debtorRef} onChange={(e) => setSection("debtor", { debtorRef: e.target.value })}/></label></fieldset>
    <fieldset><legend>4. Dívida fictícia</legend><div className="inline-fields"><label>Debt ref<input value={form.debt.debtRef} onChange={(e) => setSection("debt", { ...form.debt, debtRef: e.target.value })}/></label><label>Valor em centavos<input type="number" min="1" max="100000000" value={form.debt.amountInCents} onChange={(e) => setSection("debt", { ...form.debt, amountInCents: Number(e.target.value) })}/></label></div><label>Descrição<input value={form.debt.description} onChange={(e) => setSection("debt", { ...form.debt, description: e.target.value })}/></label><label>Vencimento<input type="date" value={form.debt.dueDate} onChange={(e) => setSection("debt", { ...form.debt, dueDate: e.target.value })}/></label></fieldset>
    <fieldset><legend>5. Propostas autorizadas</legend>{form.offers.map((offer, index) => <div className="offer-editor" key={index}><div className="inline-fields"><label>Offer ref<input value={offer.offerRef} onChange={(e) => updateOffer(index, { offerRef: e.target.value })}/></label><label>Tipo<select value={offer.kind} onChange={(e) => updateOffer(index, { kind: e.target.value as Offer["kind"] })}><option value="CASH">À vista</option><option value="INSTALLMENT">Parcelada</option></select></label></div><div className="inline-fields"><label>Total (centavos)<input type="number" min="1" value={offer.totalAmountInCents} onChange={(e) => updateOffer(index, { totalAmountInCents: Number(e.target.value) })}/></label><label>Entrada (centavos)<input type="number" min="0" value={offer.downPaymentAmountInCents} onChange={(e) => updateOffer(index, { downPaymentAmountInCents: Number(e.target.value) })}/></label><label>Parcelas<input type="number" min="1" max="120" value={offer.installmentCount} onChange={(e) => updateOffer(index, { installmentCount: Number(e.target.value) })}/></label><label>Parcela (centavos)<input type="number" min="1" value={offer.installmentAmountInCents} onChange={(e) => updateOffer(index, { installmentAmountInCents: Number(e.target.value) })}/></label></div><div className="inline-fields"><label>Primeiro vencimento<input type="date" value={offer.firstDueDate} onChange={(e) => updateOffer(index, { firstDueDate: e.target.value })}/></label><label>Expira em<input type="datetime-local" value={offer.expiresAt.slice(0,16)} onChange={(e) => updateOffer(index, { expiresAt: new Date(e.target.value).toISOString() })}/></label></div>{form.offers.length > 1 && <button type="button" className="button secondary" onClick={() => setForm((current) => ({ ...current, offers: current.offers.filter((_, position) => position !== index) }))}>Remover proposta</button>}</div>)}<button type="button" className="button secondary" onClick={() => setForm((current) => ({ ...current, offers: [...current.offers, { ...current.offers[0], offerRef: "" }] }))}>Adicionar proposta</button></fieldset>
    <label className="choice"><input type="checkbox" checked={form.demoConfirmation} readOnly/> Confirmo que o cenário é exclusivamente fictício e não contém dados pessoais reais.</label>{message && <div className="alert" role="status">{message}</div>}<div className="button-row"><button className="button primary" disabled={busy}>{busy ? "Salvando…" : editing ? "Salvar nova versão" : "Criar cenário"}</button>{editing && <button type="button" className="button secondary" onClick={() => { setEditing(undefined); setForm(empty()); }}>Cancelar edição</button>}</div></form>
    <aside className="panel scenario-list"><h2>Cenários</h2>{items.map((item) => <article className="scenario-card" key={item.profileRef}><span className={item.active ? "status-active" : "status-inactive"}>{item.active ? "Ativo" : "Inativo"}</span><h3>{item.maskedDisplayName}</h3><code>{item.demoIdentifier}</code><p>{item.creditorCount} credor · {item.debtCount} dívida · {item.offerCount} proposta(s)</p><div className="button-row"><button className="button secondary" onClick={() => edit(item.profileRef)}>Visualizar/editar</button><button className="button secondary" onClick={() => toggle(item)}>{item.active ? "Desativar" : "Ativar"}</button></div></article>)}</aside></section></main>;
}
