import type { PrismaClient } from "@/generated/prisma/client";
import { SandboxDebtProvider } from "@/modules/debt-provider/sandbox/sandbox-debt-provider";
import { describe, expect, it } from "vitest";

const challenge = { id: "challenge", challengeRef: "challenge-demo", prompt: "Qual opção fictícia?", maxAttempts: 3, status: "ACTIVE", isDemo: true, options: [{ optionRef: "option-a", label: "Azul", isCorrect: false, isDemo: true }, { optionRef: "option-b", label: "Verde", isCorrect: true, isDemo: true }] };
const offer = { offerRef: "offer-demo", kind: "CASH", totalAmountInCents: 9000, downPaymentAmountInCents: 9000, installmentCount: 1, installmentAmountInCents: 9000, firstDueDate: new Date("2099-01-10T00:00:00Z"), expiresAt: new Date("2099-01-10T23:59:59Z"), status: "AVAILABLE", recordStatus: "ACTIVE", isDemo: true, version: 3 };
const profile = { profileRef: "profile-demo", demoIdentifier: "DEMO-NOVA-001", maskedDisplayName: "Pessoa Demonstração N.", status: "ACTIVE", isDemo: true, challenge, debtors: [{ debtorRef: "debtor-demo", status: "ACTIVE", isDemo: true, creditor: { creditorRef: "creditor-demo", displayName: "Credor Demonstrativo", status: "ACTIVE", isDemo: true }, debts: [{ debtRef: "debt-demo", description: "Contrato fictício", amountInCents: 10000, dueDate: new Date("2098-01-01T00:00:00Z"), status: "OPEN", recordStatus: "ACTIVE", isDemo: true, version: 2, updatedAt: new Date("2098-01-01T00:00:00Z"), offers: [offer] }] }] };
function client() { return { sandboxIdentityProfile: { findUnique: async ({ where }: { where: { organizationId_demoIdentifier: { organizationId: string; demoIdentifier: string } } }) => where.organizationId_demoIdentifier.organizationId === "org-jf-demo" && where.organizationId_demoIdentifier.demoIdentifier === profile.demoIdentifier ? profile : null, findMany: async ({ where }: { where: { organizationId: string } }) => where.organizationId === "org-jf-demo" ? [profile] : [] }, offerAcceptance: { findFirst: async () => null } } as unknown as PrismaClient; }
const jf = { organizationId: "org-jf-demo", requestId: "request-jf" };
const atlas = { organizationId: "org-atlas-demo", requestId: "request-atlas" };

describe("SandboxDebtProvider", () => {
  it("permite identificação sem desafio somente com dados integralmente demonstrativos", async () => { const provider = new SandboxDebtProvider(client()); const identification = await provider.identifyDebtor(jf, { type: "DEMO_ID", value: profile.demoIdentifier }); const context = await provider.verifyDemoIdentifierOnly(jf, identification!.identificationRef); expect(context.authorizedAccounts).toEqual([{ debtorRef: "debtor-demo", creditorRef: "creditor-demo" }]); });
  async function verified(provider: SandboxDebtProvider) { const identification = await provider.identifyDebtor(jf, { type: "DEMO_ID", value: profile.demoIdentifier }); expect(identification).not.toBeNull(); const publicChallenge = await provider.getIdentityChallenge(jf, identification!.identificationRef); expect(publicChallenge).not.toHaveProperty("correctOptionRef"); const verification = await provider.verifyIdentity(jf, identification!.identificationRef, publicChallenge.challengeRef, "option-b"); if (!verification.verified) throw new Error("expected verified"); return verification.debtorContext; }
  it("reproduz identificação, desafio, dívida e proposta das fixtures persistidas", async () => { const provider = new SandboxDebtProvider(client(), () => new Date("2098-01-01T00:00:00Z")); const debtor = await verified(provider); const debts = await provider.listDebts(jf, debtor); expect(debts).toMatchObject([{ debtRef: "debt-demo", amount: { amountInCents: 10000, currency: "BRL" } }]); const offers = await provider.listAuthorizedOffers(jf, debtor, "debt-demo"); expect(offers[0]).toMatchObject({ offerRef: "offer-demo", providerVersion: "sandbox-offer-v3", status: "AVAILABLE", terms: { total: { amountInCents: 9000 } } }); });
  it("faz EXPIRED prevalecer pela data", async () => { const provider = new SandboxDebtProvider(client(), () => new Date("2100-01-01T00:00:00Z")); const debtor = await verified(provider); expect((await provider.getAuthorizedOffer(jf, debtor, "offer-demo")).status).toBe("EXPIRED"); });
  it("aceita idempotentemente termos canônicos e rejeita adulteração", async () => { const provider = new SandboxDebtProvider(client(), () => new Date("2098-01-01T00:00:00Z")); const debtor = await verified(provider); const current = await provider.getAuthorizedOffer(jf, debtor, "offer-demo"); const input = { idempotencyKey: "same-intention-key", offerRef: current.offerRef, expectedProviderVersion: current.providerVersion, expectedTerms: current.terms, acceptedAt: "2098-01-01T12:00:00.000Z" }; const first = await provider.acceptOffer(jf, debtor, input); expect(await provider.acceptOffer(jf, debtor, input)).toEqual(first); await expect(provider.acceptOffer(jf, debtor, { ...input, expectedTerms: { ...input.expectedTerms, installmentCount: 2 } })).rejects.toThrow("outro conteúdo"); });
  it("isola organizações mesmo com referências coincidentes", async () => { const provider = new SandboxDebtProvider(client()); expect(await provider.identifyDebtor(atlas, { type: "DEMO_ID", value: profile.demoIdentifier })).toBeNull(); const debtor = await verified(provider); await expect(provider.listDebts(atlas, debtor)).rejects.toThrow("contexto do devedor"); });
});
